In [243]:
import pandas as pd

df = pd.read_csv("../data/titanic_propre.csv")


ports = pd.DataFrame({ "embark_town": ["Southampton", "Cherbourg", "Queenstown"], "pays": ["Angleterre", "France", "Irlande"], })

nb_avant = len(df)

df = df.merge(ports, on="embark_town", how="left", validate="many_to_one")

nb_avant == len(df)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,who,embark_town,niveau_anomalie,pays
0,0,3,male,22.0,1,0,7.2500,man,Southampton,Aucune,Angleterre
1,1,1,female,38.0,1,0,71.2833,woman,Cherbourg,Aucune,France
2,1,3,female,26.0,0,0,7.9250,woman,Southampton,Aucune,Angleterre
3,1,1,female,35.0,1,0,53.1000,woman,Southampton,Aucune,Angleterre
4,0,3,male,35.0,0,0,8.0500,man,Southampton,Aucune,Angleterre

In [244]:
print(f"Il y a {len(df)} passagers à bord du Titanic, dont {df['survived'].sum()} ont survécu.")

print("\n\n% de survie selon le pays d'embarquement :\n")
display(
    df.groupby('pays')
    .agg(
        passagers = ('pays', 'size'),
        taux_survie = ('survived', 'mean')
    )
    .assign(
        taux_survie = lambda x: (x['taux_survie'] * 100).round(2)
    )
)

Il y a 891 passagers à bord du Titanic, dont 342 ont survécu.


% de survie selon le pays d'embarquement :

            passagers  taux_survie
pays
Angleterre        644        33.70
France            168        55.36
Irlande            77        38.96

Plus de la moitié des passagers provenant de France ont survécu contrairement à ceux provenant d'Angleterre ou d'Irlande avec un taux de survie aux alentours d'un tiers.

In [245]:
print("Table df : ")
display(
    df[['embark_town', 'pays']]
    .drop_duplicates()
    .sort_values('embark_town')
)

print("Table ports : ")
display(ports)

ports = ports[ports['embark_town'] != "Queenstown"]

print("Table ports après suppression de Queenstown : ")
display(ports)

df_inner = df.merge(ports, on="embark_town", how="inner", validate="many_to_one")
print(f"Il y a {len(df_inner)} passagers à bord du Titanic, dont {df_inner['survived'].sum()} ont survécu.")

Table df :

    embark_town        pays
1     Cherbourg      France
61      Inconnu         NaN
5    Queenstown     Irlande
0   Southampton  Angleterre

Table ports :

   embark_town        pays
0  Southampton  Angleterre
1    Cherbourg      France
2   Queenstown     Irlande

Table ports après suppression de Queenstown :

   embark_town        pays
0  Southampton  Angleterre
1    Cherbourg      France

Il y a 812 passagers à bord du Titanic, dont 310 ont survécu.

On remarque que le INNER permet la fusion de 2 tables en conservant uniquement les lignes d'une valeur commune aux 2 tables de la colonne qui a permis la jointure.

In [246]:
print("Table df avant la jointure :")
display(
    df[['embark_town', 'pays']]
    .drop_duplicates()
    .sort_values('embark_town')
)

print("Table ports :")
display(ports)

df_left = df.merge(
    ports,
    on="embark_town",
    how="left",
    validate="many_to_one"
)

print("Résultat de la df_left :")
display(
    df_left[['embark_town', 'pays_x', 'pays_y']]
    .drop_duplicates()
    .sort_values('embark_town')
)

print(f"Il y a {len(df_left)} passagers à bord du Titanic, dont {df_left['survived'].sum()} ont survécu.")

Table df avant la jointure :

    embark_town        pays
1     Cherbourg      France
61      Inconnu         NaN
5    Queenstown     Irlande
0   Southampton  Angleterre

Table ports :

   embark_town        pays
0  Southampton  Angleterre
1    Cherbourg      France

Résultat de la df_left :

    embark_town      pays_x      pays_y
1     Cherbourg      France      France
61      Inconnu         NaN         NaN
5    Queenstown     Irlande         NaN
0   Southampton  Angleterre  Angleterre

Il y a 891 passagers à bord du Titanic, dont 342 ont survécu.

On remarque que le LEFT conserve toutes les valeurs de la table principale. Si une valeur est commune au 2 tables, les informations de cette valeur seront intégrées au df