In [152]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

Voici la liste des colonnes où il y a des manquants:

In [153]:
df.isna().sum()[["age", "deck", "embark_town"]]

age            177
deck           688
embark_town      2
dtype: int64

In [154]:
df["age"].unique()
print("Nombre de valeurs manquantes dans la colonne 'age' avant nettoyage :", df["age"].isna().sum())

df["age"] = df["age"].fillna(df.groupby(["class", "sex"])["age"].transform("median"))

df["age"].unique()
print("Nombre de valeurs manquantes dans la colonne 'age' après nettoyage :", df["age"].isna().sum())

Nombre de valeurs manquantes dans la colonne 'age' avant nettoyage : 177
Nombre de valeurs manquantes dans la colonne 'age' après nettoyage : 0

In [155]:
df["deck"].unique()
print("Nombre de valeurs manquantes dans la colonne 'deck' avant nettoyage :", df["deck"].isna().sum())

df["deck"].value_counts(dropna=False)
df["deck"] = df["deck"].cat.add_categories(["Inconnu"]).fillna("Inconnu")
df["deck"].value_counts()

print("Nombre de valeurs manquantes dans la colonne 'deck' après nettoyage :", df["deck"].isna().sum())

Nombre de valeurs manquantes dans la colonne 'deck' avant nettoyage : 688
Nombre de valeurs manquantes dans la colonne 'deck' après nettoyage : 0

In [158]:
df["embark_town"].unique()
print("Nombre de valeurs manquantes dans la colonne 'embark_town' avant nettoyage :", df["embark_town"].isna().sum())

df["embark_town"] = df["embark_town"].fillna("Inconnu")

print("Nombre de valeurs manquantes dans la colonne 'embark_town' après nettoyage :", df["embark_town"].isna().sum())

Nombre de valeurs manquantes dans la colonne 'embark_town' avant nettoyage : 2
Nombre de valeurs manquantes dans la colonne 'embark_town' après nettoyage : 0

Examinons les doublons:

In [167]:
df.duplicated().sum()
df[df.duplicated(keep=False)].sort_values(by=list(df.columns))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
263,0,1,male,40.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True
815,0,1,male,40.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,Inconnu,Cherbourg,no,True
64,0,1,male,40.0,0,0,27.7208,C,First,man,True,Inconnu,Cherbourg,no,True
295,0,1,male,40.0,0,0,27.7208,C,First,man,True,Inconnu,Cherbourg,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,1,3,male,25.0,0,0,56.4958,S,Third,man,True,Inconnu,Southampton,yes,True
65,1,3,male,25.0,1,1,15.2458,C,Third,man,True,Inconnu,Cherbourg,yes,False
709,1,3,male,25.0,1,1,15.2458,C,Third,man,True,Inconnu,Cherbourg,yes,False
74,1,3,male,32.0,0,0,56.4958,S,Third,man,True,Inconnu,Southampton,yes,True
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,Inconnu,Southampton,yes,True

Selon moi il ne faut pas les supprimer car nous n'avons pas l'identité des passagers pour affirmer que ce sont des doublons

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Inconnu,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Inconnu,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Inconnu,Southampton,no,True